stages:          # List of stages for jobs, and their order of execution
  - validate-and-format
  - terraform:plan
  - deploy

.base-terraform:
  image: 
    name: "hashicorp/terraform"
    entrypoint: [""]
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    - terraform version
  only:
    refs: 
        - main

lint-test-job: 
  stage: validate-and-format
  extends: .base-terraform
  script:
    - terraform init
    - echo "validating code..."
    - terraform validate
    - terraform fmt -check
    - echo "terraform code valid and formatted"

tf-plan:
  stage: terraform:plan
  extends: .base-terraform
  variables:
    WORKSPACE: "plan-ws"
  script:
    - terraform init -input=false
    - terraform plan -out=${WORKSPACE}.tfplan
  artifacts:
    name: ${WORKSPACE}
    paths:
      - ./*.tfplan
      - .terraform
    expire_in: 1 week

deploy-job:
  stage: deploy  
  extends: .base-terraform
  variables:
    PLAN_FILE: plan-ws.tfplan
  script:
    - terraform init
    - echo "Deploying application..."
    - terraform apply --auto-approve ${PLAN_FILE}
    - echo "Application successfully deployed."

